import type { StillProject } from '../types';

export const stillProjects = [
  {
    kind: 'stills',
    slug: 'quiet-current',
    title: { zhHant: '靜流', en: 'QUIET CURRENT', order: 'en-zh' },
    location: { zhHant: '香港', en: 'HONG KONG', order: 'en-zh' },
    year: '2026',
    summary: {
      zhHant: '霧、水與微小身影之間，一段仍在等待正式影像的安靜習作。',
      en: 'A temporary study of distance, mist, and the quiet pull of water.',
      order: 'en-zh',
    },
    coverId: 'stills.mock.reservoir',
    index: {
      number: '01',
      mediaIds: ['stills.mock.reservoir', 'stills.mock.deep-water'],
      palette: ['#17262d', '#506976', '#aab8bd', '#d7dad7'],
      featured: true,
    },
    seo: {
      title: 'Quiet Current — Stills',
      description: 'A temporary bilingual editorial photography study for layout validation.',
      socialImageId: 'site.social-default',
    },
    blocks: [
      { id: 'opening', type: 'hero', mediaId: 'stills.mock.reservoir', titleMode: 'overlay', height: 'viewport' },
      { id: 'deep-water', type: 'fullBleed', mediaId: 'stills.mock.deep-water', height: 'natural' },
      { id: 'ice-distance', type: 'portrait', mediaId: 'stills.mock.ice-drift', width: 'medium', align: 'end' },
      {
        id: 'forest-and-rain',
        type: 'imagePair',
        mediaIds: ['stills.mock.waterfall', 'stills.mock.rain-window'],
        ratio: 'left-wide',
        align: 'center',
        gap: 'standard',
        mobile: 'stack',
      },
      {
        id: 'water-note',
        type: 'caption',
        text: { zhHant: '水面留下的，只是緩慢移動的光。', en: 'THE WATER HOLDS ONLY THE SLOW MOVEMENT OF LIGHT.' },
        align: 'center',
        width: 'small',
      },
      {
        id: 'gallery',
        type: 'imageSequence',
        mediaIds: ['stills.mock.deep-water', 'stills.mock.waterfall', 'stills.mock.ice-drift', 'stills.mock.rain-window', 'stills.mock.salt-flat'],
        presentation: 'vertical',
        gap: 'wide',
        activeRail: true,
      },
    ],
    exploreMore: ['tidal-archive', 'after-rain', 'stone-light'],
  },
  {
    kind: 'stills',
    slug: 'tidal-archive',
    title: { zhHant: '潮汐檔案', en: 'TIDAL ARCHIVE', order: 'en-zh' },
    location: { zhHant: '大嶼山', en: 'LANTAU', order: 'en-zh' },
    year: '2025',
    summary: {
      zhHant: '沙、鹽與退潮線構成一份短暫的地景索引。',
      en: 'A provisional archive of salt, sediment, and the lines left by a receding tide.',
      order: 'en-zh',
    },
    coverId: 'stills.mock.tidal-flats',
    index: {
      number: '02',
      mediaIds: ['stills.mock.tidal-flats', 'stills.mock.salt-flat'],
      palette: ['#303436', '#8f7b52', '#c2b58f', '#dce0dd'],
      featured: true,
    },
    seo: {
      title: 'Tidal Archive — Stills',
      description: 'A temporary landscape photography project used to validate varied editorial blocks.',
      socialImageId: 'site.social-default',
    },
    blocks: [
      { id: 'opening', type: 'hero', mediaId: 'stills.mock.tidal-flats', titleMode: 'overlay', height: 'viewport' },
      { id: 'salt-study', type: 'smallImage', mediaId: 'stills.mock.salt-flat', align: 'start', offset: 'small' },
      {
        id: 'mineral-triptych',
        type: 'imageTriptych',
        mediaIds: ['stills.mock.tidal-flats', 'stills.mock.salt-flat', 'stills.mock.warm-tree'],
        arrangement: 'center-tall',
        gap: 'tight',
        mobile: 'stack',
      },
      { id: 'open-water', type: 'landscape', mediaId: 'stills.mock.deep-water', width: 'large', align: 'end' },
      { id: 'breath', type: 'spacer', size: 'medium' },
      {
        id: 'gallery',
        type: 'imageSequence',
        mediaIds: ['stills.mock.tidal-flats', 'stills.mock.salt-flat', 'stills.mock.warm-tree', 'stills.mock.deep-water', 'stills.mock.ice-drift'],
        presentation: 'vertical',
        gap: 'wide',
        activeRail: true,
      },
    ],
    exploreMore: ['after-rain', 'stone-light', 'quiet-current'],
  },
  {
    kind: 'stills',
    slug: 'after-rain',
    title: { zhHant: '雨後', en: 'AFTER RAIN', order: 'en-zh' },
    location: { zhHant: '香港島', en: 'HONG KONG ISLAND', order: 'en-zh' },
    year: '2024',
    summary: {
      zhHant: '城市在雨後變得柔軟，窗光、濕牆與遠處的海彼此回應。',
      en: 'A temporary night study where wet stone, window light, and the distant harbour answer one another.',
      order: 'en-zh',
    },
    coverId: 'stills.mock.rain-passage',
    index: {
      number: '03',
      mediaIds: ['stills.mock.rain-passage', 'stills.mock.rain-window'],
      palette: ['#101820', '#25445b', '#477791', '#c28a43'],
      featured: true,
    },
    seo: {
      title: 'After Rain — Stills',
      description: 'A temporary urban photography narrative for Stills case-study validation.',
      socialImageId: 'site.social-default',
    },
    blocks: [
      { id: 'opening', type: 'hero', mediaId: 'stills.mock.rain-passage', titleMode: 'overlay', height: 'viewport' },
      {
        id: 'night-pair',
        type: 'imagePair',
        mediaIds: ['stills.mock.rain-window', 'stills.mock.rain-passage'],
        ratio: 'right-wide',
        align: 'bottom',
        gap: 'standard',
        mobile: 'stack',
      },
      {
        id: 'city-note',
        type: 'text',
        heading: { zhHant: '藍色時刻', en: 'THE BLUE HOUR' },
        body: [
          { zhHant: '雨停之後，城市的邊緣比平日更清楚。', en: 'After the rain, the city reveals its edges slowly.' },
          { zhHant: '這些影像是暫時的，最終作品仍待攝影檔案取代。', en: 'These images remain temporary until the final archive arrives.' },
        ],
        align: 'center',
        width: 'medium',
      },
      { id: 'passage', type: 'offsetImage', mediaId: 'stills.mock.rain-passage', width: 'medium', align: 'end', offset: 'large' },
      { id: 'pale-morning', type: 'fullBleed', mediaId: 'stills.mock.salt-flat', height: 'natural' },
      {
        id: 'gallery',
        type: 'imageSequence',
        mediaIds: ['stills.mock.rain-passage', 'stills.mock.rain-window', 'stills.mock.deep-water', 'stills.mock.warm-tree', 'stills.mock.waterfall'],
        presentation: 'vertical',
        gap: 'wide',
        activeRail: true,
      },
    ],
    exploreMore: ['stone-light', 'quiet-current', 'tidal-archive'],
  },
  {
    kind: 'stills',
    slug: 'stone-light',
    title: { zhHant: '石上微光', en: 'STONE LIGHT', order: 'en-zh' },
    location: { zhHant: '南丫島', en: 'LAMMA ISLAND', order: 'en-zh' },
    year: '2023',
    summary: {
      zhHant: '潮濕的林徑把光收進岩石、樹影與水聲之間。',
      en: 'A temporary woodland study of wet stone, falling water, and late amber light.',
      order: 'en-zh',
    },
    coverId: 'stills.mock.waterfall',
    index: {
      number: '04',
      mediaIds: ['stills.mock.waterfall', 'stills.mock.warm-tree'],
      palette: ['#14241d', '#395844', '#9a713e', '#d9b977'],
      featured: true,
    },
    seo: {
      title: 'Stone Light — Stills',
      description: 'A temporary woodland photography case used for responsive editorial validation.',
      socialImageId: 'site.social-default',
    },
    blocks: [
      { id: 'opening', type: 'hero', mediaId: 'stills.mock.waterfall', titleMode: 'overlay', height: 'viewport' },
      { id: 'pale-field', type: 'landscape', mediaId: 'stills.mock.salt-flat', width: 'page-wide', align: 'center' },
      { id: 'last-light', type: 'portrait', mediaId: 'stills.mock.warm-tree', width: 'large', align: 'start' },
      {
        id: 'field-note',
        type: 'caption',
        text: { zhHant: '石頭記住雨，水記住光。', en: 'STONE REMEMBERS RAIN; WATER REMEMBERS LIGHT.' },
        align: 'end',
        width: 'medium',
      },
      {
        id: 'gallery',
        type: 'imageSequence',
        mediaIds: ['stills.mock.waterfall', 'stills.mock.warm-tree', 'stills.mock.salt-flat', 'stills.mock.deep-water', 'stills.mock.reservoir'],
        presentation: 'vertical',
        gap: 'wide',
        activeRail: true,
      },
    ],
    exploreMore: ['quiet-current', 'tidal-archive', 'after-rain'],
  },
] satisfies readonly StillProject[];

export function getStillProject(slug: string): StillProject | undefined {
  return stillProjects.find((project) => project.slug === slug);
}
